### ISSUE TITLE
Questions about code

### ISSUE THREAD

**Issue by levalencia** [SharePoint/sp-dev-samples#10]
#### Category
[ x] Question
[ ] Bug
[ ] Enhancement

I was checking the code and I found something I couldnt understand, can you please explain these sections, thanks in advance.

What is spoppe.com or windows-ppe.net?
  if (new Uri(url).DnsSafeHost.Contains("spoppe.com"))
                {
                    cc = am.GetAppOnlyAuthenticatedContext(url, realm, clientId, clientSecret, acsHostUrl: "windows-ppe.net", globalEndPointPrefix: "login");
                }
                else
                {
                    cc = am.GetAppOnlyAuthenticatedContext(url, clientId, clientSecret);
                }

**Comment by frankmarasco** [comment]
Those are the Microsoft test environment endpoints that we used for testing.
