### ISSUE TITLE
Error from SharePoint Online when I try to create a new webhook

### ISSUE THREAD

**Issue by victorcea87** [SharePoint/sp-dev-samples#3]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 
#### Category

[ ] Question
[X ] Bug
[ ] Enhancement
#### Expected or Desired Behavior

I wanted to add a new subscription to a list and I expected to be added and appeared in the webhook list.
#### Observed Behavior

When I try to add a new webhook I received an internal server error from SharePoint. I can see that it doesn't arrive to send the post from SharePoint to the the api webhook when it tries to create it.
#### Steps to Reproduce

Just click on any list and add a new webhook.

**Comment by jansenbe** [comment]
Hi Victor,

Just checking: did you enable our tenant for first release? The web hooks functionality is still in developer preview and only available for tenants that are subscribed to first release. You can use your tenant admin center, search for first release and flip the switch to enable it. Note that it takes a while for everything to be setup, but typically the day after you should be good. If that's not helping please submit the actual error you get.

**Comment by VesaJuvonen** [comment]
Closing for now, due no response. We can reopen this if the first release setting was not enabled for further investigation.
